- name: Create mount directory
  file:
    path: "{{ nfs_client_mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Mount NFS share
  mount:
    path: "{{ nfs_client_mount_point }}"
    src: "{{ hostvars['prdx-nfs101'].ansible_default_ipv4.address }}:/var/nfs/shared"
    fstype: nfs
    state: mounted

