---
domain_name: "ziyotek.local"

ntp_server_ip: "192.168.29.150"
ntp_allow_network: "192.168.29.0/24"

timezone: "UTC"

firewall_allow_services:
  - ssh
  - http
  - https

nfs_client_mount_point: "/clientshare"

common_packages:
  - bind-utils
  - man
  - man-pages
  - mlocate
  - sysstat